name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to server
      run: |
        rsync -avz --delete \
          -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.PORT }}" \
          ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/${{ secrets.USERNAME }}/DevConnect

    - name: Deploy using SSH
      run: |
        ssh -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
          cd DevConnect
          docker-compose pull
          docker-compose down
          docker-compose up -d --build
        EOF
